### ISSUE TITLE
DRC Errors

### ISSUE THREAD

**Issue by Shadowtrance** [linker3000/Multicomper#1]
Came across this on easyeda when looking for retro stuff to make.
There's a few DRC errors when generating gerbers (and clicking yes to check drc) around the voltage regulator.
Are they "actually" an issue or can i just skip drc check and continue with ordering? 

Clearance (Pad - Hole)
Clearance (Hole - Pad)
Clearance (Hole - Solid Region)
Clearance (Solid Region - Pad)

I haven't changed any of the design rules on easyeda, just loaded up your project as it was.

Thanks :)

**Comment by linker3000** [comment]
> Came across this on easyeda when looking for retro stuff to make. There's a few DRC errors when generating gerbers (and clicking yes to check drc) around the voltage regulator. Are they "actually" an issue or can i just skip drc check and continue with ordering?
> 
> Clearance (Pad - Hole) Clearance (Hole - Pad) Clearance (Hole - Solid Region) Clearance (Solid Region - Pad)
> 
> I haven't changed any of the design rules on easyeda, just loaded up your project as it was.
> 
> Thanks :)

HI,

It looks like the DRC has become stricter since I last used it. It's complaining about the land set aside as a pseudo heatsink for the voltage regulator being too close to the reg's mounting hole, but that is not an issue.

I know the board works 'as is', so I don't plan to tweak the design - perhaps until/if I order a new batch. For now the DRC errors can be ignored ~~but if you want you can delete the heatsink land and the DRC errors go away~~.

[Edit: Nope, the DRC still complains that the hole is too close to the voltage regulator footprint - I'd ignore it all!]

I have just checked one of my populated boards and I didn't even bother to screw down the voltage regulator, but if you want to do that and are concerned about shorting out stuff then you could always  use a nylon nut and bolt because the regulator is unlikely to get so hot it will melt them!

If you make up a batch I hope you have fun with them!
